### ISSUE TITLE
consumer: concurrent handlers not working as expected

### ISSUE THREAD

**Issue by pajadah** [nsqio/go-nsq#256]
Hi, I have a problem on my project that are using NSQ conccurent handler.
So I am using `nsq.AddConcurrentHandlers(&MyHandler{}, 16)`. My project runs on 2 servers, so it means it will spawn 16 concurrent handlers from each server, with total of 32 handlers.
When one the topic depth is getting high (around 3 million), I check in nsqadmin that only 4 handlers out of 32 handlers are processing the messages. I wonder if there's any possible reason for this? since if I can get all that 32 handlers to process the messages, then there's won't be any high depth at all.

Here's my client code:
```
config := nsq.NewConfig()
config.DefaultRequeueDelay = 0
config.MaxAttempts = 0
config.MaxInFlight = 5000

q, err := nsq.NewConsumer("this_is_topic", "this_is_channel", config)
if err != nil {
    log.Println(err.Error())
    return
}

h := &MyHandler{
    q: q
}

q.AddConcurrentHandlers(h, 16)
q.SetLogger(log.New(os.Stderr, "nsq:", log.Ltime), nsq.LogLevelError)

err = p.connectToLookupds(q)
if err != nil {
    log.Println(err.Error())
}
```

**Comment by ploxiln** [comment]
Can you show more of your handler function? How long might it take to process a message?

MaxInFlight=5000 looks too high, you want it to be between 16 and maybe 100 depending on how many nsqd you have and how long the handler typically takes to process a message.

Setting MaxAttempts and DefaultRequeueDelay to 0 are not good ideas - I think you want MaxAttempts to be 1, and Default RequeueDelay should be positive, but you can leave it at the default and requeue with backoff=false so the consumer does not backoff when the message fails.

**Comment by ploxiln** [comment]
(can you also share stats from nsqd? and how many nsqd have this topic?)

**Comment by zihan618** [comment]
Hi, when I use `AddConcurrentHandlers`, I test  `time.Sleep(time.Second * 5) ` in consumer handler's `HandleMessage` ,  and producer generates 1 message per second.  It seems that only one comsumer is working,  and  the depth of channel msg queue  is increasing.  Why cannot the "concurrent" work?

**Comment by ploxiln** [comment]
What do you set `MaxInFlight` to? This is the other key variable to adjust for concurrent handling.

**Comment by zihan618** [comment]
> What do you set `MaxInFlight` to? This is the other key variable to adjust for concurrent handling.

Thanks! I retry my case then I find it work well. It means my last question is not the truth.   
But still in that case,  I set the consumer's `MaxInFlight` to 1 and other number,  and nsqd's  `RDC` related configs are not changed.   I see the `ready count` in nsqadmin page is always one, and actually the consumer's 5 handlers work cocurrently.

**Comment by zihan618** [comment]
> What do you set `MaxInFlight` to? This is the other key variable to adjust for concurrent handling.      
Thanks! I retry my case then I find it work well. It means my last question is not the truth.
But still in that case, I set the consumer's `MaxInFlight` to 1 and other number, and nsqd's RDC related configs are not changed.   Not matter which number I set to consumer's `MaxInFlight`, the 10 handlers can always cosume the  messages generated every second.  But if the  `MaxInFlight` is 1, in my view, the 10 handlers should work sequentially rather than in parallel.

**Comment by zihan618** [comment]
> What do you set `MaxInFlight` to? This is the other key variable to adjust for concurrent handling.

Thanks! My last question is not true.  
**My case**:
* consumer `MaxInflight`: 1 or other number less than 5
* consumer handlers:       10 handlers,  handle cost 5s
* producer:                       1 message per second
* nsqd's `MaxRdyCount` is not changed

Why can the handlers always consume the messages?  
In my view, when `MaxInflight` is 1, the handlers should work sequetially rather than in parallel.

**Comment by zihan618** [comment]
> What do you set `MaxInFlight` to? This is the other key variable to adjust for concurrent handling.

I change `MaxInFlight` and it works. Thx!! .
