### ISSUE TITLE
consumer: ConnectToNSQLookupd does not return error when nsqlookupd is not reachable

### ISSUE THREAD

**Issue by LordNoteworthy** [nsqio/go-nsq#257]
Hello,

When trying to call ConnectToNSQLookupd, even if nsqlookupd is not reachable, the function will return nil. Is that the expected behavior ?

Thanks.

**Comment by ploxiln** [comment]
Thanks for moving this issue :)

Yes, this is expected behavior.

`ConnectToNSQLookupd()` only returns an error if it cannot parse the address argument, or if the consumer is in the wrong state (for example, no message handler added).

Then, this function primarily adds this address to a list, which is used query and retry periodically. It is typical to add a handful of nsqlookupd (3 or 5 or so). Occasionally one will have to reboot or something and the query will fail, but another will work. Then the one that failed will come back but another will be temporarily out of service. So this function is not really about connecting immediately, but about adding to a list to retry periodically.

**Comment by LordNoteworthy** [comment]
Hey @ploxiln,

I was specualting you did it for a purpose, I can see it now. Thanks for your detailed answer.
