### ISSUE TITLE
Message timeout and using TOUCH

### ISSUE THREAD

**Issue by iaburton** [nsqio/go-nsq#266]
Hello,

I've recently implemented a Handler that handles messages asynchronously and had a question about message timeouts and the TOUCH command. While I will be increasing the message timeout on nsqd, according to the docs the timestamp in the message seems to be when the message was created, which gives no indication as to when the message will timeout from nsqd's perspective.

Is the correct way to go about this, assuming I want to TOUCH a message if it's about to timeout, to simply time when I receive the message? Seems like that may not align perfectly with nsqd but I'm not seeing another way. Thank you.

**Comment by ploxiln** [comment]
It would perhaps be more robust to base it on making progress. For example, if you have 10 steps to do for each message, and each step takes about 20 seconds, touch after every step completes. This depends on the task of course.

If you plan to extend the timeout of every single message you receive in the same way, then you can request a higher timeout to begin with, in the `Consumer`'s `Config.MsgTimeout`.

note that nsqd has two separate options of interest:
  * `--msg-timeout` is the default message timeout for consumers which do not specify one
  * `--max-msg-timeout` is the longest message timeout which consumers are allowed to request

**Comment by iaburton** [comment]
That makes sense, though I suppose I still need to time when I receive the message. With auto response disabled on messages (as the docs mention, to handle them async and/or in batches) I consume a certain number of messages but I may not be able to work on all of them immediately.

For more background, some consumers may batch messages (others fan out), where the first message may wait a short period before being started because the consumer was "filling" its batch (or a small timeout occurred and the batch is started early so we don't wait too long). Some of these steps may also add their own hard to predict delays, such as communicating with an external service that may take half a second to 10+ before finishing, and being unable to req/fin/touch the message until afterwards.

Of course if handling a message is taking too long you should either decrease the amount of accepted messages so fewer are waiting, and/or increase the number of workers working on them. I apply both of these, though this always seems like an edge case, which is what I'm trying to cover.

```
    // The server-side message timeout for messages delivered to this client
    MsgTimeout time.Duration `opt:"msg_timeout" min:"0"`
```
I had seen this in the consumer config docs, when I first read it I thought it was some kind of option that was pushed to the consumer/client by the server on connection (found the wording to be a bit confusing) so thank you for clarifying that, I forgot to mention it in my original post.

I think I have what I need to solve this, though I did have one more question. This is probably pretty obvious, but are there any fields in the Message type that are safe to replace/alter? The delegate seemed like the only one (maybe the body/timestamp fields too) as long as it wasn't nil and still connected to something that worked. Thanks again.

**Comment by ploxiln** [comment]
A, yes, batching, we do that sometimes too. Indeed it is based on the received time of the message, and that usually works pretty well with the time scales involved (difference in nsqd timing vs local timing might be half a second at most?) So if message timeout is 60 seconds, when I get the first message of a batch I set an internal timer for 30 seconds, and then 30 seconds later process the batch in maybe 5 or 10 seconds, still well under 60 for the oldest message.

I think you should generally should not alter any fields of the Message, not even the `Delegate` (because that is set to `producerConnDelegate` or `consumerConnDelegate` as appropriate). Just read the Body and maybe TImestamp or Attempts if they are of interest, and and use the methods. The ID might not have the properties you want (it is only unique for a particular topic on a particular nsqd). So why are all these fields public ... I guess we're just not into being strict about these things, you can mess with them if you want, and then when it breaks you can keep both pieces :)

**Comment by iaburton** [comment]
Haha I hadn't been modifying any public fields, I had looked at how nsq was implemented and it seemed dicey at best, but didn't hurt to ask. I was hoping to just overwrite the timestamp field and be lazy, but I can always wrap the nsq.Message type in something that holds the received time or whatever I need. Thank you sir :+1:
