### ISSUE TITLE
JUST WONDER WHY    PRODUCER    dose not support lookupd !  is there any official explain for this?

### ISSUE THREAD

**Issue by infynity** [nsqio/go-nsq#322]
why  only consumer  uses lookupd   ,tks

**Comment by jehiah** [comment]
@infynity I've moved this to `go-nsq` since how publishing messages is implemented is a client library concern.

Publishing messages to `nsqd` via lookupd is not supported because lookupd state is based on information about where messages are which exists after publishing messages. When a topic doesn't exist on any `nsqd` instance yet, you can't use `lookupd` to determine where the first message should be published to.

cc: #311 which is working to make it easier to publish to a pool of `nsqd` instances.

**Comment by infynity** [comment]
thanks a lot!   @jehiah  

i also saw  the code    `producer_pool` in #311  ,  i saw the commit,  but i did not find this file in master branch,  so is that means i can not use thie `producer_pool`   for now?  tks
